[info] Running exp.Main test/name.exp
[debug] Starting sandboxed run...
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug] 	C:\Users\Christian\Documents\Work\University\300 Level\Semester 2\COMP332\Mixed Week 6\comp332-week6\target\scala-2.10\classes
[debug] 	C:\Users\Christian\.sbt\boot\scala-2.10.2\lib\scala-library.jar
[debug] 	C:\Users\Christian\.ivy2\cache\com.googlecode.kiama\kiama_2.10\jars\kiama_2.10-1.5.0.jar
[debug] 	C:\Users\Christian\.ivy2\cache\org.bitbucket.inkytonik.dsinfo\dsinfo_2.10\jars\dsinfo_2.10-0.2.0.jar
[debug] 	C:\Users\Christian\.ivy2\cache\org.scala-lang\scala-reflect\jars\scala-reflect-2.10.1.jar
[debug] 	C:\Users\Christian\.ivy2\cache\org.bitbucket.inkytonik.dsprofile\dsprofile_2.10\jars\dsprofile_2.10-0.2.0.jar
[debug] 	C:\Users\Christian\.ivy2\cache\jline\jline\jars\jline-1.0.jar
[debug] Waiting for thread run-main to exit
[error] (run-main) scala.MatchError: Variable() (of class exp.SymbolTable$Variable)
scala.MatchError: Variable() (of class exp.SymbolTable$Variable)
	at exp.SemanticAnalysis$.check(SemanticAnalysis.scala:39)
	at exp.SemanticAnalysis$$anonfun$check$1.apply(SemanticAnalysis.scala:49)
	at exp.SemanticAnalysis$$anonfun$check$1.apply(SemanticAnalysis.scala:48)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at exp.SemanticAnalysis$.check(SemanticAnalysis.scala:48)
	at exp.Main$.process(Main.scala:74)
	at exp.Main$.main(Main.scala:48)
	at exp.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sbt.Run.invokeMain(Run.scala:68)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.execute$1(Run.scala:50)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:54)
	at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
	at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
[debug] 	Thread run-main exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1361)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1361)
	at scala.Option.foreach(Option.scala:197)
	at sbt.BuildCommon$class.toError(Defaults.scala:1361)
	at sbt.Defaults$.toError(Defaults.scala:34)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$27.apply(Defaults.scala:522)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$27.apply(Defaults.scala:520)
	at sbt.Scoped$$anonfun$hf5$1.apply(Structure.scala:581)
	at sbt.Scoped$$anonfun$hf5$1.apply(Structure.scala:581)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
	at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
	at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
	at sbt.std.Transform$$anon$5.work(System.scala:71)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:238)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[error] (compile:run) Nonzero exit code: 1
